#!/bin/bash
declare W_FILE

cd /opt/waifucompanion

if test ! -d venv; then
  python3 -m venv venv
  source venv/bin/activate
  for W_FILE in $(find . -name "requirements.txt"); do
    pip install -r "$W_FILE"
  done
fi

cd -

unset W_FILE

exit 0
